services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # schrodinger:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   develop:
  #     # Create a `watch` configuration to update the app
  #     watch:
  #       # Sync the working directory with the `/app` directory in the container
  #       - action: sync
  #         path: .
  #         target: /app
  #         # Exclude the project virtual environment
  #         # ignore:
  #         #   - .venv/

  #       # Rebuild the image on changes to the `pyproject.toml`
  #       - action: rebuild
  #         path: ./pyproject.toml
  #   container_name: schrodinger
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  #     - minio
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - MINIO_ENDPOINT=minio:9000
  #     - MINIO_ACCESS_KEY=minio
  #     - MINIO_SECRET_KEY=minioadmin123
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # celery-worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: celery-worker
  #   depends_on:
  #     - redis
  #     - minio
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - MINIO_ENDPOINT=minio:9000
  #     - MINIO_ACCESS_KEY=minio
  #     - MINIO_SECRET_KEY=minioadmin123
  #   command: celery -A schrodinger.celery.celery worker --loglevel=info
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "celery", "-A", "schrodinger.celery.celery", "inspect", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # celery-beat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: celery-beat
  #   depends_on:
  #     - redis
  #     - minio
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - MINIO_ENDPOINT=minio:9000
  #     - MINIO_ACCESS_KEY=minio
  #     - MINIO_SECRET_KEY=minioadmin123
  #   command: celery -A schrodinger.celery.celery beat --loglevel=info
  #   restart: unless-stopped

  flower:
    image: mher/flower:2.0.1
    container_name: flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    command: celery flower --broker=redis://redis:6379/0
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
  redis_data:
    driver: local
