"""update event columns

Revision ID: 97bc5f9cc094
Revises: 3c7dd296dd4d
Create Date: 2025-11-23 17:24:52.590171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "97bc5f9cc094"
down_revision: Union[str, Sequence[str], None] = "3c7dd296dd4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("event_type", sa.String(length=128), nullable=False)
    )
    op.add_column(
        "events", sa.Column("raw_frame_s3_key", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "events",
        sa.Column("annotated_frame_s3_key", sa.String(length=500), nullable=True),
    )
    op.drop_index(op.f("ix_events_end_time"), table_name="events")
    op.drop_index(op.f("ix_events_start_time"), table_name="events")
    op.drop_column("events", "start_time")
    op.drop_column("events", "end_time")
    op.drop_column("events", "s3_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("s3_key", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "events",
        sa.Column(
            "end_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "start_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_events_start_time"), "events", ["start_time"], unique=False
    )
    op.create_index(op.f("ix_events_end_time"), "events", ["end_time"], unique=False)
    op.drop_column("events", "annotated_frame_s3_key")
    op.drop_column("events", "raw_frame_s3_key")
    op.drop_column("events", "event_type")
    # ### end Alembic commands ###
